# Generated by Django 2.1.2 on 2018-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='在这里描述', max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('title', models.CharField(default='标题', max_length=50)),
            ],
        ),
    ]
