# Generated by Django 2.1.2 on 2018-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='text',
            field=models.TextField(default='正文'),
        ),
    ]
